# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{feed-processor}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Eden"]
  s.date = %q{2010-02-22}
  s.description = %q{Feed Processor is a multi-stage feed processor built with JRuby, MRI, beanstalk and MongoDB.}
  s.email = %q{anthonyeden@gmail.com}
  s.executables = ["fetch", "parse"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "VERSION",
     "bin/fetch",
     "bin/parse",
     "lib/feed_processor.rb",
     "lib/feed_processor/content.rb",
     "lib/feed_processor/feed.rb",
     "lib/feed_processor/fetcher.rb",
     "lib/feed_processor/file_based_request_generator.rb",
     "lib/feed_processor/parser.rb",
     "lib/feed_processor/response.rb",
     "lib/feed_processor/util.rb"
  ]
  s.homepage = %q{http://github.com/aeden/feed-processor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A multi-stage feed processor.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

